### ISSUE TITLE
Unable to generate a URL in 1.0.0

### ISSUE THREAD

**Issue by jarekkowol** [Sylius/SyliusShopApiPlugin#211]
Hello, I noticed exceptions after upgrade:

```
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "liip_imagine_filter" as such route does not exist.").
in vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_images.html.twig (line 3)
```

**Comment by lchrusciel** [comment]
It is not related to ShopApiPlugin. As an exception says the problem is inside ShopBundle(so the main repository). You can fix it by adding importing liip imagine routing in your project. For more info, please check [this PR](https://github.com/Sylius/Sylius/commit/7b042d13a8a6d116cb34cd1bf130864700b49395#diff-828ad3929c2c6e3ba47c513ec3625631R184) or [Sylius UPGRADE file](https://github.com/Sylius/Sylius/blob/master/UPGRADE.md).
